# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 584)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/gjg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 0, 141, 581))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(30, 160, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/huanjing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 240, 75, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/kongzhi.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 310, 75, 23))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/shebei.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 390, 75, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/geren.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 141, 101))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(10, 210, 118, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(10, 290, 118, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(10, 360, 118, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(10, 440, 118, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.widget)
        self.line_8.setGeometry(QtCore.QRect(10, 140, 118, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 110, 581, 471))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_6 = QtWidgets.QWidget(self.page)
        self.widget_6.setGeometry(QtCore.QRect(40, 60, 491, 281))
        self.widget_6.setObjectName("widget_6")
        self.line_9 = QtWidgets.QFrame(self.widget_6)
        self.line_9.setGeometry(QtCore.QRect(37, 80, 421, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_16 = QtWidgets.QFrame(self.widget_6)
        self.line_16.setGeometry(QtCore.QRect(37, 170, 421, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_15 = QtWidgets.QFrame(self.widget_6)
        self.line_15.setGeometry(QtCore.QRect(37, 120, 421, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_14 = QtWidgets.QFrame(self.widget_6)
        self.line_14.setGeometry(QtCore.QRect(167, 90, 20, 131))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_10 = QtWidgets.QFrame(self.widget_6)
        self.line_10.setGeometry(QtCore.QRect(30, 90, 20, 131))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_2 = QtWidgets.QLabel(self.widget_6)
        self.label_2.setGeometry(QtCore.QRect(47, 190, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setGeometry(QtCore.QRect(357, 190, 101, 16))
        self.label_19.setObjectName("label_19")
        self.line_11 = QtWidgets.QFrame(self.widget_6)
        self.line_11.setGeometry(QtCore.QRect(37, 210, 421, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(77, 100, 54, 12))
        self.label_16.setObjectName("label_16")
        self.line_13 = QtWidgets.QFrame(self.widget_6)
        self.line_13.setGeometry(QtCore.QRect(307, 90, 20, 131))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setGeometry(QtCore.QRect(47, 150, 111, 16))
        self.label.setObjectName("label")
        self.label_18 = QtWidgets.QLabel(self.widget_6)
        self.label_18.setGeometry(QtCore.QRect(357, 100, 101, 16))
        self.label_18.setObjectName("label_18")
        self.label_15 = QtWidgets.QLabel(self.widget_6)
        self.label_15.setGeometry(QtCore.QRect(357, 150, 101, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.widget_6)
        self.label_17.setGeometry(QtCore.QRect(227, 100, 54, 12))
        self.label_17.setObjectName("label_17")
        self.line_12 = QtWidgets.QFrame(self.widget_6)
        self.line_12.setGeometry(QtCore.QRect(450, 90, 20, 131))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.layoutWidget_6 = QtWidgets.QWidget(self.widget_6)
        self.layoutWidget_6.setGeometry(QtCore.QRect(40, 30, 130, 22))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_6)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 140, 61, 23))
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 190, 61, 23))
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_3 = GraphicsLayoutWidget(self.page_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 110, 561, 261))
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 50, 130, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(270, 50, 111, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 410, 101, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(160, 50, 111, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.layoutWidget_7 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(380, 50, 152, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_8.addWidget(self.label_25)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 447, 268))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.layoutWidget_5 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(40, 60, 130, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setGeometry(QtCore.QRect(60, 100, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(60, 140, 54, 12))
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.page_4)
        self.line.setGeometry(QtCore.QRect(60, 120, 171, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_4)
        self.line_2.setGeometry(QtCore.QRect(60, 170, 171, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page_4)
        self.line_3.setGeometry(QtCore.QRect(60, 220, 171, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(self.page_4)
        self.label_9.setGeometry(QtCore.QRect(120, 100, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(120, 140, 101, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 190, 75, 23))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Administrator/Pictures/xiugai.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_4)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(169, 0, 551, 101))
        self.widget_4.setObjectName("widget_4")
        self.widget_2 = QtWebEngineWidgets.QWebEngineView(self.widget_4)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 290, 101))
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(450, 0, 101, 101))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setGeometry(QtCore.QRect(293, 1, 151, 41))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setGeometry(QtCore.QRect(290, 60, 151, 41))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Lora系统"))
        self.pushButton.setText(_translate("Form", "环境检测"))
        self.pushButton_2.setText(_translate("Form", "灌溉控制"))
        self.pushButton_3.setText(_translate("Form", "设备工况"))
        self.pushButton_4.setText(_translate("Form", "个人中心"))
        self.label_2.setText(_translate("Form", "灌溉控制：手动控制"))
        self.label_19.setText(_translate("Form", "2020/02/12 19:21"))
        self.label_16.setText(_translate("Form", "控制状态"))
        self.label.setText(_translate("Form", "灌溉控制：自动控制"))
        self.label_18.setText(_translate("Form", "最近一次操作时间"))
        self.label_15.setText(_translate("Form", "2019/12/12 09:21"))
        self.label_17.setText(_translate("Form", "开关操作"))
        self.label_20.setText(_translate("Form", "地块位置："))
        self.comboBox_3.setItemText(0, _translate("Form", "大棚一"))
        self.comboBox_3.setItemText(1, _translate("Form", "大棚二"))
        self.comboBox_3.setItemText(2, _translate("Form", "大棚三"))
        self.label_5.setText(_translate("Form", "地块位置："))
        self.comboBox.setItemText(0, _translate("Form", "大棚一"))
        self.comboBox.setItemText(1, _translate("Form", "大棚二"))
        self.comboBox.setItemText(2, _translate("Form", "大棚三"))
        self.label_6.setText(_translate("Form", "当前湿度："))
        self.label_24.setText(_translate("Form", "50%"))
        self.pushButton_5.setText(_translate("Form", "数据导出为Excel"))
        self.label_7.setText(_translate("Form", "当前温度："))
        self.label_23.setText(_translate("Form", "25°C"))
        self.label_13.setText(_translate("Form", "当前二氧化碳浓度："))
        self.label_25.setText(_translate("Form", "800ppm"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "传感器名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "监测名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "最近检测值"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "时间"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_12.setText(_translate("Form", "地块位置："))
        self.comboBox_2.setItemText(0, _translate("Form", "大棚一"))
        self.comboBox_2.setItemText(1, _translate("Form", "大棚二"))
        self.comboBox_2.setItemText(2, _translate("Form", "大棚三"))
        self.label_8.setText(_translate("Form", "用户名："))
        self.label_10.setText(_translate("Form", "密码："))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.pushButton_6.setText(_translate("Form", "资料修改"))

from PyQt5 import QtWebEngineWidgets
from pyqtgraph import GraphicsLayoutWidget
